### ISSUE TITLE
请问是基于哪个版本的Cloud作为服务运行的呢？

### ISSUE THREAD

**Issue by MiderWong** [cll123456/rouyi-cloud-vue3#1]
我部署了最新的Cloud服务，但是无法成功运行，比如说验证码获取，cloud接口地址为/code，你这里使用captchaImage，还有login，cloud是/auth/login，你是对cloud服务做了二次修改吗？

**Comment by cll123456** [comment]
@MiderWong 您好，我前端代码的api层基于[springcloud](https://gitee.com/y_project/RuoYi-Cloud)里面来的，但是我没有启动后台服务。所以后面我就决定3调用在线的演示的服务。所以您可能需要对api层进行修改，方法的属性不需要。就地址需要修改下。

**Comment by MiderWong** [comment]
我看了官方demo，由于分离版本与cloud版本界面上没有区别，所以他们没有为Cloud版本单独部署服务，所以你对接的其实是前后端分离版本的api，不是cloud版本的api，cloud版本与vue版本的接口区别还挺大，所以我服务用cloud版本，ui用你这个版本无法成功对接。

**Comment by cll123456** [comment]
主要是官方没有cloud的演示服务，然后个人服务器配置太低，启动不了cloud版本。api我看了，除了登录，获取用户信息，获取权限等几个主要的接口的地址不一样外，其他的都一样的。你可以自己根据实际情况改下。

**Comment by cll123456** [comment]
或者本周末我在代码上改一下联调的接口，然后代码更新，演示环境不更新

**Comment by MiderWong** [comment]
恩，辛苦大神，谢谢开源。
